package convexhull;

import java.awt.Toolkit;

/**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
* Class: About
* File: About.java
* Description: Helping user to understand about this program 
* subject of project Countries 
* @author: Edgar Hyeongwoo Park
* Environment: MacBook, Mac OS El Capitan, jdk1.8, NetBeans 7.0
* Date: 25/04/2016
* @version 1.0
* @see javax.swing.JFrame
* History Log: 25/04/2016
*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
public class About extends javax.swing.JFrame {

    /**
     * Creates new form About
     */
    public About() {
        initComponents();
        
                // Set icon image
                 this.setIconImage(Toolkit.getDefaultToolkit().getImage("src/resource/convexhull.png"));
                 // Set okJButton as default
                 this.getRootPane().setDefaultButton(closeJButton);
                 // Set title
                 this.setTitle("Convex Hull About");
                 // Center the form and set the focus 
                 this.setLocationRelativeTo(null);
                 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeJButton = new javax.swing.JButton();
        discriptionJScrollPane = new javax.swing.JScrollPane();
        descriptionJTextArea = new javax.swing.JTextArea();
        nameJLabel = new javax.swing.JLabel();
        logoJLabel = new javax.swing.JLabel();
        copyrightJLabel = new javax.swing.JLabel();
        warningJLabel = new javax.swing.JLabel();
        vendorJLabel = new javax.swing.JLabel();
        versionJLabel = new javax.swing.JLabel();
        warningJLabel1 = new javax.swing.JLabel();
        authorJLabel = new javax.swing.JLabel();
        convexhullJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        closeJButton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        closeJButton.setMnemonic('C');
        closeJButton.setText("Close");
        closeJButton.setToolTipText("Exit");
        closeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeJButtonActionPerformed(evt);
            }
        });

        descriptionJTextArea.setEditable(false);
        descriptionJTextArea.setBackground(new java.awt.Color(204, 204, 204));
        descriptionJTextArea.setColumns(20);
        descriptionJTextArea.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        descriptionJTextArea.setRows(5);
        descriptionJTextArea.setText("In mathematics, the convex hull or convex envelope of a set X of \npoints in the Euclidean plane or Euclidean space is the smallest \nconvex set that contains X. For instance, when X is a bounded \nsubset of the plane, the convex hull may be visualized as the \nshape enclosed by a rubber band stretched around X.\nFormally, the convex hull may be defined as the intersection \nof all convex sets containing X or as the set of all convex \ncombinations of points in X. \nWith the latter definition, convex hulls may be extended from \nEuclidean spaces to arbitrary real vector spaces; they may also \nbe generalized further, to oriented matroids.\nThe algorithmic problem of finding the convex hull of a finite \nset of points in the plane or other low-dimensional Euclidean \nspaces is one of the fundamental problems of computational geometry.\n\n");
        descriptionJTextArea.setToolTipText("Description ");
        descriptionJTextArea.setAutoscrolls(false);
        descriptionJTextArea.setCaretColor(new java.awt.Color(204, 204, 204));
        discriptionJScrollPane.setViewportView(descriptionJTextArea);

        nameJLabel.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        nameJLabel.setText("About : Convex Hull ");
        nameJLabel.setToolTipText("Title");

        copyrightJLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        copyrightJLabel.setText("Copyright : Free");
        copyrightJLabel.setToolTipText("copy free");

        warningJLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        warningJLabel.setText("Warning   :   ...");
        warningJLabel.setToolTipText("no warning");

        vendorJLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        vendorJLabel.setText("vendor :  Edgar Hyeongwoo Park");
        vendorJLabel.setToolTipText("inventor name ");

        versionJLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        versionJLabel.setText("Product version :          1.1");
        versionJLabel.setToolTipText("version");

        warningJLabel1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        warningJLabel1.setText("Warning : No Copyright - Free to use");
        warningJLabel1.setToolTipText("No Copy");

        authorJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        authorJLabel.setText("Created by: Edgar Hyeongwoo Park");
        authorJLabel.setToolTipText("Created by: Edgar Hyeongwoo Park");

        convexhullJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/convexhull.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vendorJLabel)
                                    .addComponent(versionJLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(266, 266, 266)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(copyrightJLabel)
                                            .addComponent(warningJLabel))))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(nameJLabel)
                                .addGap(27, 27, 27)))
                        .addComponent(logoJLabel)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(authorJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(warningJLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(closeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(discriptionJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(convexhullJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(logoJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nameJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(copyrightJLabel)
                            .addComponent(versionJLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vendorJLabel)
                            .addComponent(warningJLabel))))
                .addGap(18, 18, 18)
                .addComponent(convexhullJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(discriptionJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(warningJLabel1)
                    .addComponent(authorJLabel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
     * Method: closeJButtonActionPerformed
     * closing this form 
     * @param evt 
     * @return void
     */
    private void closeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeJButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();//exit

    }//GEN-LAST:event_closeJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new About().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorJLabel;
    private javax.swing.JButton closeJButton;
    private javax.swing.JLabel convexhullJLabel;
    private javax.swing.JLabel copyrightJLabel;
    private javax.swing.JTextArea descriptionJTextArea;
    private javax.swing.JScrollPane discriptionJScrollPane;
    private javax.swing.JLabel logoJLabel;
    private javax.swing.JLabel nameJLabel;
    private javax.swing.JLabel vendorJLabel;
    private javax.swing.JLabel versionJLabel;
    private javax.swing.JLabel warningJLabel;
    private javax.swing.JLabel warningJLabel1;
    // End of variables declaration//GEN-END:variables
}
